CREATE TABLE public."traseul" (
	id serial4 NOT NULL,
	traseul int4 NULL,
	masina varchar(20) NULL,
	nr_masina varchar(20) NULL,
	CONSTRAINT trs_pkey PRIMARY KEY (id)
);

CREATE TABLE public.soferi (
	id serial4 NOT NULL,
	nume varchar(20) NOT NULL,
	prenume varchar(20) NOT NULL,
	trs_id int4 NOT NULL,
	CONSTRAINT soferi_pkey PRIMARY KEY (id),
	CONSTRAINT soferi_trs_id_fkey FOREIGN KEY (trs_id) REFERENCES public."traseul"(id)
);


INSERT INTO "public"."traseul" (TRASEUL,MASINA,NR_MASINA) VALUES
	 (101,'autobuz','GL-01-PMG'),
	 (102,'autobuz','GL-02-PMG'),
	 (103,'autobuz','GL-03-PMG'),
	 (104,'autobuz','GL-04-PMG'),
	 (105,'autobuz','GL-05-PMG'),
	 (106,'autobuz','GL-06-PMG'),
	 (107,'autobuz','GL-07-PMG'),
	 (108,'autobuz','GL-08-PMG'),
	 (109,'autobuz','GL-09-PMG'),
	 (110,'troleibuz','GL-1401'),
	 (111,'troleibuz','GL-1402'),
	 (112,'troleibuz','GL-1403'),
	 (113,'troleibuz','GL-1404'),
	 (114,'troleibuz','GL-1405'),
	 (115,'troleibuz','GL-1406'),
	 (116,'troleibuz','GL-1407'),
	 (117,'troleibuz','GL-1408'),
	 (118,'troleibuz','GL-1409');


INSERT INTO "public"."soferi" (NUME,PRENUME,TRS_ID) VALUES
	 ('ANGHEL','GABRIEL',1),
	 ('ARITON','GEORGEL-MARIUS',2),
	 ('ASLAN','FLORIN',3),
	 ('AVRAM','CEZAR-PANAITE',4),
	 ('BADIU','VALERICA-MARCELA',5),
	 ('BADIU','LUCIANA',5),
	 ('BARBU','ZAHARIA',7),
	 ('BARBU','MARICICA',8),
	 ('BORDEA','MIHAITA-VALENTIN',9),
	 ('BOTEZATU','VASILE',10),
	 ('BUCIUMAN','GEORGE',11),
	 ('BUCSA','IONEL',12),
	 ('BULAI','GEORGEL-ADRIAN',13),
	 ('CATEA','ALIN-IONUT',14),
	 ('CHIOREANU','SORIN-ALEXANDRU',15),
	 ('CIOLACU','GICU-AUREL',16),
	 ('CIRINBEI','SILVIU',17),
	 ('CIUPERCA','VASILE',18),
	 ('CRISTEA','IULIAN',17),
	 ('CRISTEA','VIOREL',16),
	 ('CRISTEA','ANDREEA',15),
	 ('CRISU','FLORIN-CRISTIAN',14),
	 ('CRISU','STEFAN',13),
	 ('CUCIUREANU','COSTEL-CRISTIAN',12),
	 ('DANILA','FLORIN-CIPRIAN',11),
	 ('DIMA','COSTEL',10),
	 ('DINU','TEODOR',9),
	 ('DINU','GHIORGHE',8),
	 ('DRAGAN','MIHAI-SILVIU',7),
	 ('DRAGOMIR','ADRIAN-FLORIN',6),
	 ('FILIP','MARIUS-ANDREI',5),
	 ('FRAGA','CLAUDIU',4),
	 ('GHEORGHE','SILVIU',3),
	 ('GHEORGHITA','VASILE',2),
	 ('GHEORGHITA','LILIANA',1),
	 ('GHEORGHITA','NELA-MARCELA',18),
	 ('GHIOCA','VASILE',17),
	 ('GRAUR','PAUL',16),
	 ('GRECU','FRASINICA',15),
	 ('GRECU','GEORGEL',14),
	 ('HARUTI','NICUSOR',13),
	 ('HEUX','YANNIS',12),
	 ('IFTIMIE','STELIAN',11),
	 ('IGNAT','VIOREL',10),
	 ('ILIE','GIGI',9),
	 ('ILIE','CAMELIA',8),
	 ('ILIE','MIHAITA',7),
	 ('IONASCU','PETRISOR',6),
	 ('IORDACHE','FLORIN',5),
	 ('IORGA','IONUT',4),
	 ('JALBA','CRISTINA-OANA',3),
	 ('LATU','MARIAN-FLORIN',2),
	 ('LAZAR','LUCIAN',1),
	 ('LUNGU','ADRIAN-VALENTIN',2),
	 ('LUNGU','DORU',3),
	 ('LUPU','ADRIAN',4),
	 ('MAFTEI','MIHAI-IULIAN',5),
	 ('MARACINE','ROBERTO',6),
	 ('MARIN','ADRIAN',7),
	 ('MATEI','MARILENA-NICUTA',8),
	 ('MATEI','IONEL',9),
	 ('MIHAI','IONEL',10),
	 ('MIHALACHE','PETRICA',11),
	 ('MIHALACHE','MARIA',12),
	 ('MITRAN','FLORIN',13),
	 ('MUSAT','MARIAN-NICUSOR',14),
	 ('NECULA','ELENA-IONELA',15),
	 ('NICOLAE','GEORGE',16),
	 ('NICOLAU','AUREL',17),
	 ('NITU','MARIAN',18),
	 ('PALADE','CRISTINEL',1),
	 ('PASTIA','FLORIN',2),
	 ('PATRICHE','COSMIN-FLORIN',3),
	 ('PETRESCU','VALENTINA-MARCELA',4),
	 ('POPOVICI','VALENTIN',5);

